---
- hosts: all
  tasks:

  - name: uninstall old versions
    apt:
      state: absent
      pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      
  - name: install requirements 
    apt:
      update_cache: yes
      state: present
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      
  - name: install gpg key
    apt_key:
      state: present
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      url: https://download.docker.com/linux/debian/gpg
      
  - name: add repository
    apt_repository:
      state: present
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
      
  - name: install docker engine
    apt:
      update_cache: yes
      state: present
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      
