---

- name: ensure iptables legacy binaries are installed
  apt:
    state: present
    pkg:
    - iptables
    - arptables
    - ebtables
    - apt-transport-https

- name: switch to legacy versions
  alternatives:
    name: '{{ item.name }}'
    path: '{{ item.path }}'
  with_items:
    - { name: 'iptables', path: '/usr/sbin/iptables-legacy'}
    - { name: 'ip6tables', path: '/usr/sbin/ip6tables-legacy'}
    - { name: 'arptables', path: '/usr/sbin/arptables-legacy'}
    - { name: 'ebtables', path: '/usr/sbin/ebtables-legacy'}
      
- name: install gpg key
  apt_key:
    state: present
    id: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      
- name: add repository
  apt_repository:
    state: present
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      
- name: install kubelet, kubeadm and kubectl
  apt:
    update_cache: yes
    state: present
    pkg:
    - kubelet
    - kubeadm
    - kubectl
  when: kubernetes_version is undefined

- name: install kubelet, kubeadm and kubectl
  apt:
    update_cache: yes
    state: present
    pkg:
    - kubelet={{ kubernetes_version }}
    - kubeadm={{ kubernetes_version }}
    - kubectl={{ kubernetes_version }}
  when: kubernetes_version is defined

- name: mark packages for hold
  command: apt-mark hold kubelet kubeadm kubectl
